#ifndef __CSI_CONFIG_H
#define __CSI_CONFIG_H

#define CONFIG_BOARD_NAME_STR "xiaohui_c906_evb"
#define CONFIG_SUPPORT_TSPEND 1
#define CONFIG_ARCH_INTERRUPTSTACK 4096
#define CONFIG_NEWLIB_WRAP 1
#define CONFIG_USER_DEFINED_LD_DIR_STR ""

#define CONFIG_KERNEL_RTTHREAD 1
#endif
