from building import *

Import('env')


env.Append(CPPPATH=['drv', 'include', 'core'])

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp') + Glob('*.S')
CPPPATH = [cwd]

group = DefineGroup('Board', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
